# Generated by Django 6.0.7 on 2026-07-16 14:11

import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="Title shown in the download dropdown (e.g. 'Frontend Resume').", max_length=120)),
                ('file', models.FileField(upload_to='resume/', validators=[portfolio.validators.FileValidator({'pdf'}, {'application/pdf'}, 10)])),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.ImageField(blank=True, upload_to='certificates/', validators=[portfolio.validators.FileValidator({'gif', 'jpeg', 'jpg', 'png', 'webp'}, {'image/gif', 'image/jpeg', 'image/png', 'image/webp'}, 5)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='experience/logos/', validators=[portfolio.validators.FileValidator({'gif', 'jpeg', 'jpg', 'png', 'webp'}, {'image/gif', 'image/jpeg', 'image/png', 'image/webp'}, 5)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile/', validators=[portfolio.validators.FileValidator({'gif', 'jpeg', 'jpg', 'png', 'webp'}, {'image/gif', 'image/jpeg', 'image/png', 'image/webp'}, 5)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_pdf',
            field=models.FileField(blank=True, upload_to='resume/', validators=[portfolio.validators.FileValidator({'pdf'}, {'application/pdf'}, 10)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='projects/covers/', validators=[portfolio.validators.FileValidator({'gif', 'jpeg', 'jpg', 'png', 'webp'}, {'image/gif', 'image/jpeg', 'image/png', 'image/webp'}, 5)]),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/gallery/', validators=[portfolio.validators.FileValidator({'gif', 'jpeg', 'jpg', 'png', 'webp'}, {'image/gif', 'image/jpeg', 'image/png', 'image/webp'}, 5)]),
        ),
    ]
