# Generated by Django 6.0.7 on 2026-07-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_resume_alter_certificate_certificate_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Include country code, e.g. +91 98765 43210.', max_length=20),
        ),
    ]
